### ISSUE TITLE
홈 페이지 PR 수정

### ISSUE THREAD

**Issue by Jisu0528** [2024-StudyBuddy/Front-end#26]
## Description

> #18 홈 페이지에 대한 수정 사항을 적용하여 코드를 수정하였다.
## Todo
- [x] `HOME` 타이틀 bold로 바꾸기
- [x] 이미지 버튼 사이의 간격 조정
- [x] 프로그래스바와 목표 시간 사이 간격 조정
