### ISSUE TITLE
스터디룸 설정의 스터디 도우미 ui 추가

### ISSUE THREAD

**Issue by Jisu0528** [2024-StudyBuddy/Front-end#47]
## Description

> 스터디룸 설정의 스터디 도우미 선택 ui를 추가한다.

## Todo
- [x] tab component에 `3. 스터디 도우미` 추가
- [x] 스터디 도우미 ui 구현
- [x] 이전 또는 다음 버튼의 url 수정
